version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    restart: always

  flowise:
    image: flowiseai/flowise
    ports:
      - "3001:3000"
    volumes:
      - ./flowise_data:/root/.flowise
    environment:
      - PORT=3000
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
    restart: always

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres       # usuário do Postgres
      POSTGRES_PASSWORD: 123456   # senha do Postgres
      POSTGRES_DB: fluxo          # nome do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # expõe a porta 5432 para acesso externo (opcional)
      
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemplo.com    # e-mail de login no pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin            # senha de login no pgAdmin
    ports:
      - "5050:80"    # porta host:container (acesse http://localhost:5050)
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
      